<template><h1 id="svg介绍" tabindex="-1"><a class="header-anchor" href="#svg介绍" aria-hidden="true">#</a> svg介绍</h1>
<ul>
<li>SVG 是一种开放标准的矢量图形语言，即表示可缩放矢量图形（Scalable Vector Graphics）格式，是由万维网联盟（W3C）开发并进行维护的。</li>
<li>优点：由于 SVG 图像是矢量图像，可以无限缩小放大，所以 SVG 可以在任何分辨率的设备上高清显示，不需要再像以前一样输出各种 @2x 倍图来适配不同分辨率的屏幕。</li>
<li>SVG 有非常成熟的设计工具支持导出 SVG 的图形格式，比如，AI 或者是 Sketch 等设计软件都支持直接导出 SVG 的图形格式，非常方便。</li>
<li>SVG 的 viewBox 是一个非常强大的属性，它可以精确的控制和定义SVG的可视空间。它实际上可以看做是一个定义了可视范围的坐标系统。</li>
<li></li>
</ul>
<h2 id="画一条线" tabindex="-1"><a class="header-anchor" href="#画一条线" aria-hidden="true">#</a> 画一条线</h2>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token doctype"><span class="token punctuation">&lt;!</span><span class="token doctype-tag">DOCTYPE</span> <span class="token name">html</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>html</span><span class="token punctuation">></span></span>
	<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>head</span><span class="token punctuation">></span></span>
		<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">charset</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>utf-8<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
		<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>title</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>title</span><span class="token punctuation">></span></span>
		<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>style</span><span class="token punctuation">></span></span><span class="token style"><span class="token language-css">
			
			<span class="token selector">.svg1 line</span> <span class="token punctuation">{</span>
				<span class="token comment">/* 排列方式按照实线为10间隔为10的方式排列下去 */</span>
			    <span class="token property">stroke-dasharray</span><span class="token punctuation">:</span>300<span class="token punctuation">;</span>  
				<span class="token comment">/* 定义 dash 线条开始的位置  */</span>
			    <span class="token property">stroke-dashoffset</span><span class="token punctuation">:</span>300<span class="token punctuation">;</span>
				<span class="token property">animation</span><span class="token punctuation">:</span> stroke 0.6s linear forwards<span class="token punctuation">;</span>     
			<span class="token punctuation">}</span>
			<span class="token atrule"><span class="token rule">@keyframes</span> stroke</span> <span class="token punctuation">{</span>
			  <span class="token selector">100%</span> <span class="token punctuation">{</span>
			    <span class="token property">stroke-dashoffset</span><span class="token punctuation">:</span> 0<span class="token punctuation">;</span>
			  <span class="token punctuation">}</span>
			<span class="token punctuation">}</span>
		</span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>style</span><span class="token punctuation">></span></span>
	<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>head</span><span class="token punctuation">></span></span>
	<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>body</span><span class="token punctuation">></span></span>
		
		
		<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>svg</span> <span class="token attr-name">x</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>0px<span class="token punctuation">"</span></span> <span class="token attr-name">y</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>0px<span class="token punctuation">"</span></span> <span class="token attr-name">width</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>300px<span class="token punctuation">"</span></span> <span class="token attr-name">height</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>100px<span class="token punctuation">"</span></span> <span class="token attr-name">viewBox</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>0 0 300 100<span class="token punctuation">"</span></span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>svg1<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
		  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>line</span> <span class="token attr-name">x1</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>0<span class="token punctuation">"</span></span> <span class="token attr-name">y1</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>0<span class="token punctuation">"</span></span> <span class="token attr-name">x2</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>300<span class="token punctuation">"</span></span> <span class="token attr-name">y2</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>0<span class="token punctuation">"</span></span> <span class="token attr-name">stroke</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>#000<span class="token punctuation">"</span></span> <span class="token attr-name">stroke-width</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>1<span class="token punctuation">"</span></span> <span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>line</span><span class="token punctuation">></span></span>
		<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>svg</span><span class="token punctuation">></span></span>
		
		
	<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>body</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>html</span><span class="token punctuation">></span></span>

</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br></div></div><h2 id="画一个圆" tabindex="-1"><a class="header-anchor" href="#画一个圆" aria-hidden="true">#</a> 画一个圆</h2>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code>	<span class="token doctype"><span class="token punctuation">&lt;!</span><span class="token doctype-tag">DOCTYPE</span> <span class="token name">html</span><span class="token punctuation">></span></span>
		<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>html</span><span class="token punctuation">></span></span>
			<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>head</span><span class="token punctuation">></span></span>
				<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">charset</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>utf-8<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
				<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>title</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>title</span><span class="token punctuation">></span></span>
				<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>style</span><span class="token punctuation">></span></span><span class="token style"><span class="token language-css">
					 <span class="token selector">.checkmark</span> <span class="token punctuation">{</span>     <span class="token comment">/* 画布位置 */</span>
					  <span class="token property">width</span><span class="token punctuation">:</span> 56px<span class="token punctuation">;</span>
					  <span class="token property">height</span><span class="token punctuation">:</span> 56px<span class="token punctuation">;</span>
					  <span class="token property">display</span><span class="token punctuation">:</span> block<span class="token punctuation">;</span>
					  <span class="token property">margin</span><span class="token punctuation">:</span> 10% auto<span class="token punctuation">;</span>
					<span class="token punctuation">}</span>
					<span class="token selector">.checkmark__circle</span> <span class="token punctuation">{</span>
					  <span class="token property">stroke-dasharray</span><span class="token punctuation">:</span> 180<span class="token punctuation">;</span>
					  <span class="token property">stroke-dashoffset</span><span class="token punctuation">:</span>180<span class="token punctuation">;</span>
					  <span class="token comment">/* 用来设置 dasharray 定义 dash 线条开始的位置 */</span>
					  <span class="token property">stroke-width</span><span class="token punctuation">:</span> 2<span class="token punctuation">;</span>
					  <span class="token property">stroke</span><span class="token punctuation">:</span> #7ac142<span class="token punctuation">;</span>
					  <span class="token property">fill</span><span class="token punctuation">:</span> none<span class="token punctuation">;</span>
					  <span class="token comment">/* 不填充 */</span>
					  <span class="token property">animation</span><span class="token punctuation">:</span> stroke 0.6s linear forwards<span class="token punctuation">;</span>     
					  <span class="token comment">/* forwards是停在动画最后的的那个画面。 */</span>
					<span class="token punctuation">}</span>
					<span class="token atrule"><span class="token rule">@keyframes</span> stroke</span> <span class="token punctuation">{</span>
					  <span class="token selector">100%</span> <span class="token punctuation">{</span>
					    <span class="token property">stroke-dashoffset</span><span class="token punctuation">:</span> 0<span class="token punctuation">;</span>
					  <span class="token punctuation">}</span>
					<span class="token punctuation">}</span>
					
				</span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>style</span><span class="token punctuation">></span></span>
			<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>head</span><span class="token punctuation">></span></span>
			<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>body</span><span class="token punctuation">></span></span>
				
				
				<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>svg</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkmark<span class="token punctuation">"</span></span> <span class="token attr-name">xmlns</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>http://www.w3.org/2000/svg<span class="token punctuation">"</span></span> <span class="token attr-name">viewBox</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>0 0 56 56<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
				  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>circle</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkmark__circle<span class="token punctuation">"</span></span> <span class="token attr-name">cx</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>26<span class="token punctuation">"</span></span> <span class="token attr-name">cy</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>26<span class="token punctuation">"</span></span> <span class="token attr-name">r</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>25<span class="token punctuation">"</span></span> <span class="token attr-name">fill</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>none<span class="token punctuation">"</span></span><span class="token punctuation">/></span></span>
				  <span class="token comment">&lt;!-- &lt;path class="checkmark__check" fill="none" d="M14.1 27.2l7.1 7.2 16.7-16.8"/> --></span>
				<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>svg</span><span class="token punctuation">></span></span>
				
				
			<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>body</span><span class="token punctuation">></span></span>
		<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>html</span><span class="token punctuation">></span></span>
	
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br></div></div><h2 id="画一个成功的动画" tabindex="-1"><a class="header-anchor" href="#画一个成功的动画" aria-hidden="true">#</a> 画一个成功的动画</h2>
<ul>
<li>我只需要在 AI 等矢量设计软件中绘制该图形，然后导出 SVG 代码就可以了</li>
</ul>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token doctype"><span class="token punctuation">&lt;!</span><span class="token doctype-tag">DOCTYPE</span> <span class="token name">html</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>html</span><span class="token punctuation">></span></span>
	<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>head</span><span class="token punctuation">></span></span>
		<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">charset</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>utf-8<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
		<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>title</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>title</span><span class="token punctuation">></span></span>
		<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>style</span><span class="token punctuation">></span></span><span class="token style"><span class="token language-css">
		    <span class="token selector">.checkmark__circle</span> <span class="token punctuation">{</span>
		      <span class="token property">stroke-dasharray</span><span class="token punctuation">:</span> 166<span class="token punctuation">;</span>
		      <span class="token property">stroke-dashoffset</span><span class="token punctuation">:</span> 166<span class="token punctuation">;</span>
		      <span class="token property">stroke-width</span><span class="token punctuation">:</span> 2<span class="token punctuation">;</span>
		      <span class="token property">stroke</span><span class="token punctuation">:</span> #7ac142<span class="token punctuation">;</span>
		      <span class="token property">fill</span><span class="token punctuation">:</span> none<span class="token punctuation">;</span>
		      <span class="token property">animation</span><span class="token punctuation">:</span> stroke 0.6s <span class="token function">cubic-bezier</span><span class="token punctuation">(</span>0.65<span class="token punctuation">,</span> 0<span class="token punctuation">,</span> 0.45<span class="token punctuation">,</span> 1<span class="token punctuation">)</span> forwards<span class="token punctuation">;</span>
		    <span class="token punctuation">}</span>
		    
		    <span class="token selector">.checkmark</span> <span class="token punctuation">{</span>
		      <span class="token property">width</span><span class="token punctuation">:</span> 56px<span class="token punctuation">;</span>
		      <span class="token property">height</span><span class="token punctuation">:</span> 56px<span class="token punctuation">;</span>
		      <span class="token property">border-radius</span><span class="token punctuation">:</span> 50%<span class="token punctuation">;</span>
		      <span class="token property">display</span><span class="token punctuation">:</span> block<span class="token punctuation">;</span>
		      <span class="token property">stroke-width</span><span class="token punctuation">:</span> 2<span class="token punctuation">;</span>
		      <span class="token property">stroke</span><span class="token punctuation">:</span> #fff<span class="token punctuation">;</span>
		      <span class="token property">margin</span><span class="token punctuation">:</span> 10% auto<span class="token punctuation">;</span>
		      <span class="token property">box-shadow</span><span class="token punctuation">:</span> inset 0px 0px 0px #7ac142<span class="token punctuation">;</span>
		      <span class="token property">animation</span><span class="token punctuation">:</span> fill .4s ease-in-out .4s forwards<span class="token punctuation">,</span> scale .3s ease-in-out .9s both<span class="token punctuation">;</span>
		    <span class="token punctuation">}</span>
		    
		    <span class="token selector">.checkmark__check</span> <span class="token punctuation">{</span>
		      <span class="token property">transform-origin</span><span class="token punctuation">:</span> 50% 50%<span class="token punctuation">;</span>
		      <span class="token property">stroke-dasharray</span><span class="token punctuation">:</span> 48<span class="token punctuation">;</span>
		      <span class="token property">stroke-dashoffset</span><span class="token punctuation">:</span> 48<span class="token punctuation">;</span>
		      <span class="token property">animation</span><span class="token punctuation">:</span> stroke 0.3s <span class="token function">cubic-bezier</span><span class="token punctuation">(</span>0.65<span class="token punctuation">,</span> 0<span class="token punctuation">,</span> 0.45<span class="token punctuation">,</span> 1<span class="token punctuation">)</span> 0.8s forwards<span class="token punctuation">;</span>
		    <span class="token punctuation">}</span>
		    
		    <span class="token atrule"><span class="token rule">@keyframes</span> stroke</span> <span class="token punctuation">{</span>
		      <span class="token selector">100%</span> <span class="token punctuation">{</span>
		        <span class="token property">stroke-dashoffset</span><span class="token punctuation">:</span> 0<span class="token punctuation">;</span>
		      <span class="token punctuation">}</span>
		    <span class="token punctuation">}</span>
		    <span class="token atrule"><span class="token rule">@keyframes</span> scale</span> <span class="token punctuation">{</span>
		      <span class="token selector">0%, 100%</span> <span class="token punctuation">{</span>
		        <span class="token property">transform</span><span class="token punctuation">:</span> none<span class="token punctuation">;</span>
		      <span class="token punctuation">}</span>
		      <span class="token selector">50%</span> <span class="token punctuation">{</span>
		        <span class="token property">transform</span><span class="token punctuation">:</span> <span class="token function">scale3d</span><span class="token punctuation">(</span>1.1<span class="token punctuation">,</span> 1.1<span class="token punctuation">,</span> 1<span class="token punctuation">)</span><span class="token punctuation">;</span>
		      <span class="token punctuation">}</span>
		    <span class="token punctuation">}</span>
		    <span class="token atrule"><span class="token rule">@keyframes</span> fill</span> <span class="token punctuation">{</span>
		      <span class="token selector">100%</span> <span class="token punctuation">{</span>
		        <span class="token property">box-shadow</span><span class="token punctuation">:</span> inset 0px 0px 0px 30px #7ac142<span class="token punctuation">;</span>
		      <span class="token punctuation">}</span>
		    <span class="token punctuation">}</span>
	
			
		</span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>style</span><span class="token punctuation">></span></span>
	<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>head</span><span class="token punctuation">></span></span>
	<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>body</span><span class="token punctuation">></span></span>
		
		<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>svg</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkmark<span class="token punctuation">"</span></span> <span class="token attr-name">xmlns</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>http://www.w3.org/2000/svg<span class="token punctuation">"</span></span> <span class="token attr-name">viewBox</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>0 0 52 52<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
		  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>circle</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkmark__circle<span class="token punctuation">"</span></span> <span class="token attr-name">cx</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>26<span class="token punctuation">"</span></span> <span class="token attr-name">cy</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>26<span class="token punctuation">"</span></span> <span class="token attr-name">r</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>25<span class="token punctuation">"</span></span> <span class="token attr-name">fill</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>none<span class="token punctuation">"</span></span><span class="token punctuation">/></span></span>
		  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>path</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkmark__check<span class="token punctuation">"</span></span> <span class="token attr-name">fill</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>none<span class="token punctuation">"</span></span> <span class="token attr-name">d</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>M14.1 27.2l7.1 7.2 16.7-16.8<span class="token punctuation">"</span></span><span class="token punctuation">/></span></span>
		<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>svg</span><span class="token punctuation">></span></span>
		
	<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>body</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>html</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br><span class="line-number">44</span><br><span class="line-number">45</span><br><span class="line-number">46</span><br><span class="line-number">47</span><br><span class="line-number">48</span><br><span class="line-number">49</span><br><span class="line-number">50</span><br><span class="line-number">51</span><br><span class="line-number">52</span><br><span class="line-number">53</span><br><span class="line-number">54</span><br><span class="line-number">55</span><br><span class="line-number">56</span><br><span class="line-number">57</span><br><span class="line-number">58</span><br><span class="line-number">59</span><br><span class="line-number">60</span><br><span class="line-number">61</span><br><span class="line-number">62</span><br><span class="line-number">63</span><br><span class="line-number">64</span><br><span class="line-number">65</span><br></div></div></template>
