<template><h1 id="vant移动端适配问题" tabindex="-1"><a class="header-anchor" href="#vant移动端适配问题" aria-hidden="true">#</a> vant移动端适配问题</h1>
<p>1、首先vant的ui样式中的大小都是以px结尾的并是以375的屏幕为基准的，所以当我们对样式进行rem转换时就要考虑到这个问题，如果UI设计稿的屏幕大小也是375那就不能做转换区分直接如下配置：<br>
在.postcssrc.js中进行配置：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>module<span class="token punctuation">.</span>exports <span class="token operator">=</span> <span class="token punctuation">{</span>
  <span class="token string-property property">"plugins"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token string-property property">'autoprefixer'</span><span class="token operator">:</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">browsers</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">'Android >= 4.0'</span><span class="token punctuation">,</span> <span class="token string">'iOS >= 8'</span><span class="token punctuation">]</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token string-property property">'postcss-pxtorem'</span><span class="token operator">:</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">rootValue</span><span class="token operator">:</span> <span class="token number">37.5</span><span class="token punctuation">,</span>
      <span class="token literal-property property">propList</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">'*'</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
      <span class="token literal-property property">exclude</span><span class="token operator">:</span> <span class="token string">"styles|element-ui|Front|manage|errorLog|errorPage|layout|login|components"</span>    <span class="token comment">//不需要转为REM的文件名，如果项目中包含多端是配的话可以利用此配置</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><p>如果UI设计稿的大小和vant的设计稿的大小不一致的话，参考以下配置：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>
<span class="token keyword">const</span> AutoPrefixer <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">"autoprefixer"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> px2rem <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">"postcss-pxtorem"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
module<span class="token punctuation">.</span><span class="token function-variable function">exports</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> file <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">let</span> remUnit<span class="token punctuation">;</span> <span class="token comment">// 判断条件 </span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>file <span class="token operator">&amp;&amp;</span> file<span class="token punctuation">.</span>dirname <span class="token operator">&amp;&amp;</span> file<span class="token punctuation">.</span>dirname<span class="token punctuation">.</span><span class="token function">indexOf</span><span class="token punctuation">(</span><span class="token string">"vant"</span><span class="token punctuation">)</span> <span class="token operator">></span> <span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> remUnit <span class="token operator">=</span> <span class="token number">37.5</span><span class="token punctuation">;</span> <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span> remUnit <span class="token operator">=</span> <span class="token number">75</span><span class="token punctuation">;</span> <span class="token punctuation">}</span>
  <span class="token keyword">return</span> <span class="token punctuation">{</span>
    <span class="token literal-property property">plugins</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token function">px2rem</span><span class="token punctuation">(</span><span class="token punctuation">{</span> <span class="token literal-property property">remUnit</span><span class="token operator">:</span> remUnit<span class="token punctuation">,</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token function">AutoPrefixer</span><span class="token punctuation">(</span><span class="token punctuation">{</span> <span class="token literal-property property">browsers</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"last 20 versions"</span><span class="token punctuation">,</span> <span class="token string">"android >= 4.0"</span><span class="token punctuation">]</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">]</span>
  <span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token comment">//如果看到红字 warn这是因为 autoprefixer 版本问题导致的，把上面的 browsers 替换为 overrideBrowserslist 就可以了</span>
<span class="token keyword">const</span> AutoPrefixer <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">"autoprefixer"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> px2rem <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">"postcss-pxtorem"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
module<span class="token punctuation">.</span><span class="token function-variable function">exports</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> file <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">let</span> remUnit<span class="token punctuation">;</span> <span class="token comment">// 判断条件 请自行调整 我使用的是 mand-mobile ui 没有对vant引入进行测试 </span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>file <span class="token operator">&amp;&amp;</span> file<span class="token punctuation">.</span>dirname <span class="token operator">&amp;&amp;</span> file<span class="token punctuation">.</span>dirname<span class="token punctuation">.</span><span class="token function">indexOf</span><span class="token punctuation">(</span><span class="token string">"vant"</span><span class="token punctuation">)</span> <span class="token operator">></span> <span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> remUnit <span class="token operator">=</span> <span class="token number">37.5</span><span class="token punctuation">;</span> <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span> remUnit <span class="token operator">=</span> <span class="token number">75</span><span class="token punctuation">;</span> <span class="token punctuation">}</span>
  <span class="token keyword">return</span> <span class="token punctuation">{</span>
    <span class="token literal-property property">plugins</span><span class="token operator">:</span> <span class="token punctuation">[</span>
      <span class="token function">px2rem</span><span class="token punctuation">(</span><span class="token punctuation">{</span> <span class="token literal-property property">remUnit</span><span class="token operator">:</span> remUnit<span class="token punctuation">,</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
      <span class="token function">AutoPrefixer</span><span class="token punctuation">(</span><span class="token punctuation">{</span> <span class="token literal-property property">overrideBrowserslist</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"last 20 versions"</span><span class="token punctuation">,</span> <span class="token string">"android >= 4.0"</span><span class="token punctuation">]</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">]</span>
  <span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br></div></div><h2 id="vant样式大小转为rem后弹出框字体模糊的问题" tabindex="-1"><a class="header-anchor" href="#vant样式大小转为rem后弹出框字体模糊的问题" aria-hidden="true">#</a> vant样式大小转为rem后弹出框字体模糊的问题</h2>
<p>由于设置了 transform: translate3d(-50%,-50%,0);在设置 transform时 div的宽度或者高度并不是偶数，移动50%之后，像素点并不是整数，出了小数，和显示像素没有对上，所以弹出框的字体出现了模糊问题，解决方案如下：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>  <span class="token literal-property property">position</span><span class="token operator">:</span> absolute<span class="token punctuation">;</span>  
  <span class="token literal-property property">left</span><span class="token operator">:</span><span class="token number">0</span> <span class="token operator">!</span>important<span class="token punctuation">;</span>             
  <span class="token literal-property property">right</span><span class="token operator">:</span><span class="token number">0</span><span class="token punctuation">;</span>
  <span class="token literal-property property">margin</span><span class="token operator">:</span>auto<span class="token punctuation">;</span> 
  <span class="token literal-property property">transform</span><span class="token operator">:</span> <span class="token function">translate3d</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span><span class="token number">0</span><span class="token punctuation">,</span><span class="token number">0</span><span class="token punctuation">)</span> <span class="token operator">!</span>important<span class="token punctuation">;</span>  <span class="token comment">//这里很重要取消了移动</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div></template>
