<template><h1 id="设计模式" tabindex="-1"><a class="header-anchor" href="#设计模式" aria-hidden="true">#</a> 设计模式</h1>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">//  单例模式</span>
 <span class="token keyword">function</span> <span class="token function">people</span><span class="token punctuation">(</span><span class="token parameter">name</span><span class="token punctuation">)</span><span class="token punctuation">{</span>    
     <span class="token keyword">this</span><span class="token punctuation">.</span>name <span class="token operator">=</span> name
     <span class="token keyword">this</span><span class="token punctuation">.</span>gods <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>
     <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function-variable function">buy</span><span class="token operator">=</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">god</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
         <span class="token keyword">this</span><span class="token punctuation">.</span>gods<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>god<span class="token punctuation">)</span>
     <span class="token punctuation">}</span>
 <span class="token punctuation">}</span>
 <span class="token keyword">let</span> jack <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">people</span><span class="token punctuation">(</span><span class="token string">'jack'</span><span class="token punctuation">)</span>

 jack<span class="token punctuation">.</span><span class="token function">buy</span><span class="token punctuation">(</span><span class="token string">'apple'</span><span class="token punctuation">)</span>
 jack<span class="token punctuation">.</span><span class="token function">buy</span><span class="token punctuation">(</span><span class="token string">'orange'</span><span class="token punctuation">)</span>

console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>jack<span class="token punctuation">.</span>gods<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// 策略模式</span>
<span class="token keyword">const</span> sumMoney <span class="token operator">=</span> <span class="token punctuation">{</span>
    <span class="token function-variable function">meituan</span><span class="token operator">:</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">money</span><span class="token punctuation">)</span><span class="token punctuation">{</span><span class="token keyword">return</span> money <span class="token operator">*</span> <span class="token number">0.8</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token function-variable function">elma</span><span class="token operator">:</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">money</span><span class="token punctuation">)</span><span class="token punctuation">{</span><span class="token keyword">return</span> money <span class="token operator">*</span> <span class="token number">0.85</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token function-variable function">paotui</span><span class="token operator">:</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">money</span><span class="token punctuation">)</span><span class="token punctuation">{</span><span class="token keyword">return</span> money <span class="token operator">*</span> <span class="token number">0.9</span><span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token keyword">const</span> <span class="token function-variable function">choicePlatform</span> <span class="token operator">=</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">platname<span class="token punctuation">,</span>money</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">return</span> sumMoney<span class="token punctuation">[</span>platname<span class="token punctuation">]</span><span class="token punctuation">(</span>money<span class="token punctuation">)</span>
<span class="token punctuation">}</span>

console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token function">choicePlatform</span><span class="token punctuation">(</span><span class="token string">'meituan'</span><span class="token punctuation">,</span><span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token function">choicePlatform</span><span class="token punctuation">(</span><span class="token string">'elma'</span><span class="token punctuation">,</span><span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token function">choicePlatform</span><span class="token punctuation">(</span><span class="token string">'paotui'</span><span class="token punctuation">,</span><span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">)</span>

<span class="token comment">// 观察者模式</span>
    <span class="token keyword">class</span> <span class="token class-name">oneteam</span><span class="token punctuation">{</span>    
       <span class="token function">constructor</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
         <span class="token keyword">this</span><span class="token punctuation">.</span>people <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>
       <span class="token punctuation">}</span> 
       <span class="token function">sendMessage</span><span class="token punctuation">(</span><span class="token parameter">msg</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
          <span class="token keyword">this</span><span class="token punctuation">.</span>people<span class="token punctuation">.</span><span class="token function">forEach</span><span class="token punctuation">(</span><span class="token parameter">val</span><span class="token operator">=></span><span class="token punctuation">{</span>
            val<span class="token punctuation">.</span><span class="token function">updateMsg</span><span class="token punctuation">(</span>msg<span class="token punctuation">)</span>
          <span class="token punctuation">}</span><span class="token punctuation">)</span>
       <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">class</span> <span class="token class-name">people</span><span class="token punctuation">{</span>
      <span class="token function">constructor</span><span class="token punctuation">(</span><span class="token parameter">name<span class="token punctuation">,</span>team</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
        <span class="token keyword">this</span><span class="token punctuation">.</span>name <span class="token operator">=</span> name
        <span class="token keyword">this</span><span class="token punctuation">.</span>team <span class="token operator">=</span> team
        <span class="token keyword">this</span><span class="token punctuation">.</span>team<span class="token punctuation">.</span>people<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">)</span>
      <span class="token punctuation">}</span>
      <span class="token function">updateMsg</span><span class="token punctuation">(</span><span class="token parameter">msg</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
          console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">this</span><span class="token punctuation">.</span>name<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">收到</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>msg<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">通知</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">let</span> s1 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">oneteam</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

    <span class="token keyword">let</span> jack <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">people</span><span class="token punctuation">(</span><span class="token string">'jack'</span><span class="token punctuation">,</span>s1<span class="token punctuation">)</span>
    <span class="token keyword">let</span> tom <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">people</span><span class="token punctuation">(</span><span class="token string">'tom'</span><span class="token punctuation">,</span>s1<span class="token punctuation">)</span>
    <span class="token keyword">let</span> alice <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">people</span><span class="token punctuation">(</span><span class="token string">'alice'</span><span class="token punctuation">,</span>s1<span class="token punctuation">)</span>
   
    s1<span class="token punctuation">.</span><span class="token function">sendMessage</span><span class="token punctuation">(</span><span class="token string">'开会了'</span><span class="token punctuation">)</span>
    s1<span class="token punctuation">.</span><span class="token function">sendMessage</span><span class="token punctuation">(</span><span class="token string">'吃饭'</span><span class="token punctuation">)</span>


</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br><span class="line-number">44</span><br><span class="line-number">45</span><br><span class="line-number">46</span><br><span class="line-number">47</span><br><span class="line-number">48</span><br><span class="line-number">49</span><br><span class="line-number">50</span><br><span class="line-number">51</span><br><span class="line-number">52</span><br><span class="line-number">53</span><br><span class="line-number">54</span><br><span class="line-number">55</span><br><span class="line-number">56</span><br><span class="line-number">57</span><br><span class="line-number">58</span><br><span class="line-number">59</span><br><span class="line-number">60</span><br><span class="line-number">61</span><br><span class="line-number">62</span><br><span class="line-number">63</span><br></div></div></template>
