<template><h1 id="时间相关操作" tabindex="-1"><a class="header-anchor" href="#时间相关操作" aria-hidden="true">#</a> 时间相关操作</h1>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code> <span class="token keyword">function</span> <span class="token function">timestampToTime</span> <span class="token punctuation">(</span><span class="token parameter">timestamp</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>  <span class="token comment">//将时间戳转为日期   </span>
    <span class="token keyword">const</span> dateObj <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">(</span><span class="token operator">+</span>timestamp<span class="token punctuation">)</span> <span class="token comment">// ps, 必须是数字类型，不能是字符串, +运算符把字符串转化为数字，更兼容</span>
    <span class="token keyword">const</span> year <span class="token operator">=</span> dateObj<span class="token punctuation">.</span><span class="token function">getFullYear</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment">// 获取年，</span>
    <span class="token keyword">const</span> month <span class="token operator">=</span> dateObj<span class="token punctuation">.</span><span class="token function">getMonth</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token number">1</span> <span class="token comment">// 获取月，必须要加1，因为月份是从0开始计算的</span>
    <span class="token keyword">const</span> date <span class="token operator">=</span> dateObj<span class="token punctuation">.</span><span class="token function">getDate</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment">// 获取日，记得区分getDay()方法是获取星期几的。</span>
    <span class="token keyword">const</span> hours <span class="token operator">=</span> <span class="token function">pad</span><span class="token punctuation">(</span>dateObj<span class="token punctuation">.</span><span class="token function">getHours</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>  <span class="token comment">// 获取时, pad函数用来补0</span>
    <span class="token keyword">const</span> minutes <span class="token operator">=</span>  <span class="token function">pad</span><span class="token punctuation">(</span>dateObj<span class="token punctuation">.</span><span class="token function">getMinutes</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// 获取分</span>
    <span class="token keyword">const</span> seconds <span class="token operator">=</span>  <span class="token function">pad</span><span class="token punctuation">(</span>dateObj<span class="token punctuation">.</span><span class="token function">getSeconds</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// 获取秒</span>
    <span class="token keyword">return</span> year <span class="token operator">+</span> <span class="token string">'-'</span> <span class="token operator">+</span> month <span class="token operator">+</span> <span class="token string">'-'</span> <span class="token operator">+</span> date <span class="token operator">+</span> <span class="token string">' '</span> <span class="token operator">+</span> hours <span class="token operator">+</span> <span class="token string">':'</span> <span class="token operator">+</span> minutes <span class="token operator">+</span> <span class="token string">':'</span> <span class="token operator">+</span> seconds
<span class="token punctuation">}</span>

<span class="token keyword">function</span> <span class="token function">pad</span><span class="token punctuation">(</span><span class="token parameter">str</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token operator">+</span>str <span class="token operator">>=</span> <span class="token number">10</span> <span class="token operator">?</span> str <span class="token operator">:</span> <span class="token string">'0'</span> <span class="token operator">+</span> str
<span class="token punctuation">}</span>

 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token function">timestampToTime</span><span class="token punctuation">(</span><span class="token number">1597299460734</span><span class="token punctuation">)</span><span class="token punctuation">)</span>  <span class="token comment">//将时间戳转为日期   </span>

 <span class="token keyword">let</span> myDate <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span> 
 
 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>myDate<span class="token punctuation">.</span><span class="token function">getTime</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// 获取当前时间时间戳</span>

 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>myDate<span class="token punctuation">)</span> <span class="token comment">// 获取标准时间格式</span>

 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>Date<span class="token punctuation">.</span><span class="token function">parse</span><span class="token punctuation">(</span>myDate<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// 将标准时间格式转为时间戳</span>

 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>myDate<span class="token punctuation">.</span><span class="token function">toLocaleString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// 获取当前日期和时间</span>

 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>myDate<span class="token punctuation">.</span><span class="token function">toLocaleDateString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">//获取当前日期</span>

 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>myDate<span class="token punctuation">.</span><span class="token function">toLocaleTimeString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">////获取当前时间</span>

 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>myDate<span class="token punctuation">.</span><span class="token function">getYear</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">/////获取当前年份(2位)</span>

 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>myDate<span class="token punctuation">.</span><span class="token function">getFullYear</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">////获取完整的年份(4位,1970-????)</span>

 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>myDate<span class="token punctuation">.</span><span class="token function">getMonth</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">////获取当前月份(0-11,0代表1月)</span>

 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>myDate<span class="token punctuation">.</span><span class="token function">getDate</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">////获取当前日(1-31)</span>

 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>myDate<span class="token punctuation">.</span><span class="token function">getDay</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">////获取当前星期X(0-6,0代表星期天)</span>

 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>myDate<span class="token punctuation">.</span><span class="token function">getTime</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">////获取当前时间(从1970.1.1开始的毫秒数)</span>

 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>myDate<span class="token punctuation">.</span><span class="token function">getHours</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">////获取当前小时数(0-23)</span>

 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>myDate<span class="token punctuation">.</span><span class="token function">getMinutes</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">////获取当前分钟数(0-59)</span>

 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>myDate<span class="token punctuation">.</span><span class="token function">getSeconds</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">////获取当前秒数(0-59)</span>

 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>myDate<span class="token punctuation">.</span><span class="token function">getMilliseconds</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">////获取当前毫秒数(0-999)</span>
 
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br><span class="line-number">44</span><br><span class="line-number">45</span><br><span class="line-number">46</span><br><span class="line-number">47</span><br><span class="line-number">48</span><br><span class="line-number">49</span><br><span class="line-number">50</span><br><span class="line-number">51</span><br></div></div></template>
